### PR TITLE
change fonts

### PR DESCRIPTION
**Pull request by topepo**
How does this look?

old:
image

new: 
image

### CODE REVIEW

**Comment by juliasilge** [comment]
I really like the font! 🙌 I do think the slide titles should be heavier than they are in "new:" so the slides don't look so monotonous, more like in "old:". Does this font have a bold or heavy version?

**Comment by juliasilge** [comment]
Thanks for taking a look at this @EmilHvitfeldt when you get a chance!

**Comment by EmilHvitfeldt** [comment]
I bumped up the font weight of DM Sans to 500 and it now looks clover to the weight we had before

Screen Shot 2022-06-07 at 1 08 58 PM
Screen Shot 2022-06-07 at 1 09 08 PM

**Review by juliasilge — APPROVED** [review]
Looks fantastic! 🙌 

Thank you both so much.

**Comment by juliasilge** [comment]
I will re-render soon.

image

**Pull request merged**
