### PR TITLE
transition from rpart.plot to partykit

### LINKED ISSUE #163: use different package than rpart.plot to plot decision trees
Follow up with Max on which package this is. :)

### PR DESCRIPTION
**Pull request by simonpcouch**
Closes #163. They do look good!

This also removes the redundant `library()` calls in "What makes a model" to make space for that additional `as.party.rpart()` line.

### CODE REVIEW

**Comment by hfrick** [comment]
Generally on-board 👍 

does this render for you? I tried and had it crash at lines 571-577 🤔 

there is a note leftover about `roundint = FALSE` only being used to quiet a warning, let's remove that too

**Comment by simonpcouch** [comment]
Oh, me too. Looks like partykit doesn't know what to do with an engine fit that was fitted within a workflow:

``` r
library(tidymodels)
library(partykit)
#> Loading required package: grid
#> Loading required package: libcoin
#> Loading required package: mvtnorm

tree_fit_formula <-
  decision_tree("regression") %>% 
  fit(mpg ~ ., data = mtcars) 

tree_fit_formula %>%
  extract_fit_engine() %>%
  as.party.rpart()
#> 
#> Model formula:
#> mpg ~ cyl + disp + hp + drat + wt + qsec + vs + am + gear + carb
#> 
#> Fitted party:
#> [1] root
#> |   [2] cyl >= 5
#> |   |   [3] hp >= 192.5: 13.414 (n = 7, err = 28.8)
#> |   |   [4] hp < 192.5: 18.264 (n = 14, err = 59.9)
#> |   [5] cyl < 5: 26.664 (n = 11, err = 203.4)
#> 
#> Number of inner nodes:    2
#> Number of terminal nodes: 3

tree_fit_wflow <-
  workflow(mpg ~ ., decision_tree("regression")) %>% 
  fit(data = mtcars) 

tree_fit_wflow %>%
  extract_fit_engine() %>%
  as.party.rpart()
#> Error in model.frame.default(formula = ..y ~ cyl + disp + hp + drat + : 'data' must be a data.frame, environment, or list
```

<sup>Created on 2023-07-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Tried adjusting the `data` argument in `as.party.rpart`, which seemed relevant, to no avail.🤔

I'd say we ought not to use both partykit and rpart to plot these trees as a workaround here. Should we just close this PR? Or see if we can track down the issue in workflows?

**Comment by simonpcouch** [comment]
After some discussion with Hannah, we've decided we'll opt to continue using rpart.plot.🏄

**Comment by hfrick** [comment]
Ah, Simon is 🏎️  😄

**Pull request closed without merging**
