### PR TITLE
add additional caution not to `extract_*()` -> `predict()`

### LINKED ISSUE #164: add slide cautioning not to predict with engine fit
Immediately after introducing `extract_*()` methods and talking about how great they are, make sure people don't predict with them! In "What makes a model."

### PR DESCRIPTION
**Pull request by simonpcouch**
Closes #164.🦋

### CODE REVIEW

**Comment by simonpcouch** [comment]
Fine with me if this PR is ~too much caution~, feel free to close in that case. :)

**Review by hfrick — COMMENTED** [review]
We should definitely say that somewhere. I think once is enough though - but let's put it on the teaching slide instead of the exercise slide. On the exercise slide, I would offer some guidance on alternatives for what to do with the engine fit, e.g. does it have a plot method?

**Comment by simonpcouch** [comment]
You got it!

I wonder if this exercise might feel better with _just_ asking folks to extract the object and bump down to 2 or 3 minutes, and then follow up with

https://github.com/tidymodels/workshops/blob/f33f23d13a8ae622d38ef482fe30dcdc8af43b6c/slides/03-what-makes-a-model.qmd#L636

**Comment by hfrick** [comment]
I think of the attendees of this course as people who are probably familiar with single model fit objects like an engine fit so exploring that should be something that they are more familiar than with tidymodels objects. Given that, I think leaving more room to explore is a good thing. 

But if we want to give us a bit more flexibility to adapt the exercise on the fly to the attendees in the room: Let's reduce the prompt and time in the slides, because it's easier to extend it on the fly than cut down.

**Comment by hfrick** [comment]
But I'm fine with either version, go ahead and merge after you made your choice 🌳

**Review by hfrick — APPROVED** [review]

**Pull request merged**
