### PR TITLE
Posit 2023 minutia

### PR DESCRIPTION
**Pull request by topepo**
Makes sure that countdown is always loaded. 

Also, the `hotel_rates` data set is modified and keeps the same name. I added `data(hotel_rates)` before the first usages that that errors don't occur if someone runs that first chunk more than once.

### CODE REVIEW

**Review by simonpcouch — CHANGES_REQUESTED** [review]
Thumbs up to the hotel data changes!

We should be fine already on the countdown loading via `setup.R`, though:

https://github.com/tidymodels/workshops/blob/9ff132c9ce552aab5efa2cf938cb458fbf8f8a02/slides/setup.R#L21

And then, in each file:

https://github.com/tidymodels/workshops/blob/9ff132c9ce552aab5efa2cf938cb458fbf8f8a02/slides/intro-01-introduction.qmd#L20-L23

It looks like all of the intro and advanced slides source that file already.

**Comment by topepo** [comment]
Hmm. When I was using `Run All` from the menu, it must not have been executing that. I consistently had errors from not finding the function.  

image
image

**Comment by hfrick** [comment]
yes, that's a bit annoying but I just run the contents of the setup file in the R session (because it needs a few other things from there anyway, like the color definitions for the viz of the test/train split via the gray and pink squares - IIRC). I would also not necessarily put the `library(countdown)` everywhere if that's a workable solution for you?

**Comment by topepo** [comment]
I'd like to leave it in; Slack from Christophe says that it is a knitr bug that it won't work with IDE commands. 

I'm testing about a dozen files and don't want to do manual loading each time.

**Comment by topepo** [comment]
Alternatively, I could just change the function calls to be namespaced.

**Pull request merged**
