### PR TITLE
Improve reproducibility of deck 5

### PR DESCRIPTION
**Pull request by hfrick**
I added several seeds for deck 5.

For deck 6, the tune results for xgboost are not reproducible even with a seed. The resulting objects are not `identical()` but `waldo::compare()` says there are no differences. Is that a known thing and we just need to set some xgboost option?

### CODE REVIEW

**Comment by juliasilge** [comment]
Let's talk about what to do about the xgboost results in our meeting, maybe?

**Comment by juliasilge** [comment]
It might be easier to only change the `.qmd` and then render from main.

**Comment by hfrick** [comment]
what's the easiest for this? close this PR and open an new one with just the .qmd changes?

**Comment by juliasilge** [comment]
Honestly that is probably easiest. (You _can_ remove files from a PR but it's sort of fussy.)

**Pull request closed without merging**
